### ISSUE TITLE
out of range panic while logging

### ISSUE THREAD

**Issue by dukhyungkim** [dukhyungkim/fn#1]
```
ERRO[2023-05-14T09:55:30Z] api error                                     action="server.(*Server).handleFnInvokeCall-fm" code=502 error="function failed" fn_id=01GXNC1P08NG9000GZJ0000003
panic: runtime error: slice bounds out of range [:577] with capacity 480


goroutine 433368797 [running]:
bytes.(*Buffer).grow(0xc0012ea2a0, 0x1d0)
	/usr/local/go/src/bytes/buffer.go:146 +0x1ed
bytes.(*Buffer).Write(0xc0012ea2a0, {0xc000c44008, 0x1d0, 0xc0001f6000?})
	/usr/local/go/src/bytes/buffer.go:170 +0x66
github.com/dukhyungkim/fn/api/agent.(*limitDiscardWriter).Write(0xc00074abe0, {0xc000c44008?, 0x1d0, 0xc0001f61d0?})
	/go/src/github.com/fnproject/fn/api/agent/func_logger.go:200 +0x6b
github.com/dukhyungkim/fn/api/agent.multiWriteCloser.Write(...)
	/go/src/github.com/fnproject/fn/api/agent/func_logger.go:98
github.com/dukhyungkim/fn/api/common.(*ghostWriter).Write(0xc00057fce0?, {0xc000c44008, 0x1d0, 0x8001})
	/go/src/github.com/fnproject/fn/api/common/io_utils.go:195 +0x48
github.com/docker/docker/pkg/stdcopy.StdCopy({0x7f20db689e20, 0xc00034b680}, {0x7f20db689e20, 0xc00034b680}, {0x1245a40, 0xc00057fce0})
	/go/pkg/mod/github.com/docker/docker@v23.0.3+incompatible/pkg/stdcopy/stdcopy.go:174 +0x31f
github.com/fsouza/go-dockerclient.(*Client).hijack.func1.1()
	/go/pkg/mod/github.com/fsouza/go-dockerclient@v1.9.7/client.go:820 +0xc5
created by github.com/fsouza/go-dockerclient.(*Client).hijack.func1
	/go/pkg/mod/github.com/fsouza/go-dockerclient@v1.9.7/client.go:806 +0x2aa
```

**Comment by dukhyungkim** [comment]
```
panic: runtime error: slice bounds out of range [603:0]

goroutine 79814092 [running]:
bytes.(*Buffer).Bytes(...)
    /usr/local/go/src/bytes/buffer.go:54
github.com/dukhyungkim/fn/api/agent.(*lineWriter).Write(0xc0002d5980, {0xc0008d6008?, 0x25b, 0xc0008d6000?})
    /go/src/github.com/fnproject/fn/api/agent/func_logger.go:142 +0x165
github.com/dukhyungkim/fn/api/agent.multiWriteCloser.Write(...)
    /go/src/github.com/fnproject/fn/api/agent/func_logger.go:98
github.com/dukhyungkim/fn/api/common.(*ghostWriter).Write(0xc0006d8f00?, {0xc0008d6008, 0x25b, 0x8001})
    /go/src/github.com/fnproject/fn/api/common/io_utils.go:195 +0x48
github.com/docker/docker/pkg/stdcopy.StdCopy({0x7fdddc548bc8, 0xc00033e600}, {0x7fdddc548bc8, 0xc00033e600}, {0x1245a40, 0xc0006d8f00})
    /go/pkg/mod/github.com/docker/docker@v23.0.3+incompatible/pkg/stdcopy/stdcopy.go:174 +0x31f
github.com/fsouza/go-dockerclient.(*Client).hijack.func1.1()
    /go/pkg/mod/github.com/fsouza/go-dockerclient@v1.9.7/client.go:820 +0xc5
created by github.com/fsouza/go-dockerclient.(*Client).hijack.func1
    /go/pkg/mod/github.com/fsouza/go-dockerclient@v1.9.7/client.go:806 +0x2aa
```

**Comment by dukhyungkim** [comment]
```
ERRO[2023-05-13T16:10:20Z] api error                                     action="server.(*Server).handleFnInvokeCall-fm" code=502 error="function failed" fn_id=01GXQCECRRNG90010ZJ0004F2N
panic: runtime error: slice bounds out of range [113:0]

goroutine 47924609 [running]:
bytes.(*Buffer).Bytes(...)
	/usr/local/go/src/bytes/buffer.go:54
github.com/dukhyungkim/fn/api/agent.(*lineWriter).Write(0xc00021e600, {0xc00061e008?, 0x71, 0xc00061e000?})
	/go/src/github.com/fnproject/fn/api/agent/func_logger.go:142 +0x165
github.com/dukhyungkim/fn/api/agent.multiWriteCloser.Write(...)
	/go/src/github.com/fnproject/fn/api/agent/func_logger.go:98
github.com/dukhyungkim/fn/api/common.(*ghostWriter).Write(0xc000752480?, {0xc00061e008, 0x71, 0x8001})
	/go/src/github.com/fnproject/fn/api/common/io_utils.go:195 +0x48
github.com/docker/docker/pkg/stdcopy.StdCopy({0x7f5e6aa26e48, 0xc0002fee20}, {0x7f5e6aa26e48, 0xc0002fee20}, {0x1245a40, 0xc000752480})
	/go/pkg/mod/github.com/docker/docker@v23.0.3+incompatible/pkg/stdcopy/stdcopy.go:174 +0x31f
github.com/fsouza/go-dockerclient.(*Client).hijack.func1.1()
	/go/pkg/mod/github.com/fsouza/go-dockerclient@v1.9.7/client.go:820 +0xc5
created by github.com/fsouza/go-dockerclient.(*Client).hijack.func1
	/go/pkg/mod/github.com/fsouza/go-dockerclient@v1.9.7/client.go:806 +0x2aa
```
